apiVersion: v1
kind: Pod
metadata:
  name: sleep
  annotations:
    purpose: test
  labels:
    app: 'sleep'
spec:
  containers:
  - name: sleep
    image: beekman9527/sleep
    resources:
      requests:
        memory: "10Mi"
      limits:
        memory: "50Mi"

