kind: Service
apiVersion: v1
metadata:
  name: mysql-exporter
spec:
  selector:
    app: mysql-exporter-songbin
  type: ClusterIP
  ports:
  - name: http
    protocol: TCP
    port: 9104
    targetPort: 9104
