apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: song
  annotations:
    sidecar.istio.io/inject: "false"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
