apiVersion: v1
kind: ReplicationController
metadata:
  name: memg-30
spec:
  replicas: 1
  selector:
    app: mem-30-group-child
  template:
    metadata:
      name: mem-30-group
      labels:
        app: mem-30-group-child
    spec:
      containers:
      - name: mem-load
        image: beekman9527/cpumemload:latest
        resources:
          limits:
            memory: "40Mi"
            cpu: "10m"
        env:
        - name: RUN_TYPE
          value: "memory"
        - name: MEMORY_NUM
          value: "10"
