apiVersion: v1
kind: Pod
metadata:
  name: test-get-pods2 
spec:
  serviceAccount: turbo-user
  containers:
  - name: test-pod
    image: beekman9527/kubelet-pod:curl 
    imagePullPolicy: Always
    args:
    - --v=4
    - --kubeletHttps=true
    - --kubeletPort=10250
